# Generated by Django 5.2.3 on 2025-06-30 17:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='limbs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='homepage',
            name='warn_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
