# Generated by Django 5.2.3 on 2025-07-02 19:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_limbs_homepage_warn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='err_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='limbs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
